package Stuff;

public enum EActions {
    WAIT,
    WAS_HERE,
    LOOKED,
    TIMESCIP,
    TOOK_BOOK,
    BUSY,
    VIEWERS_WAIT,
    STARTED_TO_READ,
    CANT_SAY,
    DISAPPEARED,
    DOUBT,
    HEAD_ACTION,
    EYES_ACTION,
    CHOKED,
    COMFORT,
    READ_ON_WALK,
    RETURNED,
    TO_HOP_ON,
    TO_BREAK,
    TOUCHED,
    RIDE,
    RIDE_CALL,
    FIND,
    SEND_A_MESSAGE,
    APPEARED,
    SAID_THAT,
    WAKED,
    SAW,
    DESCRIBE,
    WALKED_AROUND,
    DESCRIBE2;
}
